/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Messagerie;

import BDD.Bdd;
import static java.awt.Color.GREEN;
import java.awt.Component;
import java.awt.Window;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author User
 */
public class Groupe extends javax.swing.JFrame {
    
    static List<String> contactsUserCourant;
    DefaultListModel<String> listModel;
    static String emailUserCourant;

    public Groupe(List<String> listeContacts, String emailUtilisateurCourant) {
 
        emailUserCourant= emailUtilisateurCourant;
        contactsUserCourant = listeContacts;
        initComponents();
        init();
        initContact();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private void init() {
        contactsList.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        listModel = new DefaultListModel<>();
        contactsList.setModel(listModel);
        contactsList.setVisible(true);
        
    }

    private void initContact() {
        // Ajouter les éléments de contactsUserCourant à la JList
        for (String contact : contactsUserCourant) {
            listModel.addElement(contact);
        }
        contactsList.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        barreNomGroupe = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        contactsList = new javax.swing.JList<>();
        boutonCreerGroupe = new javax.swing.JButton();
        logErreurs = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bouttonFermer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Créer groupe");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });

        Jpanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nom du groupe :");

        barreNomGroupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barreNomGroupeActionPerformed(evt);
            }
        });

        contactsList.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        contactsList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(contactsList);

        boutonCreerGroupe.setBackground(new java.awt.Color(204, 255, 204));
        boutonCreerGroupe.setText("Créer groupe");
        boutonCreerGroupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonCreerGroupeActionPerformed(evt);
            }
        });

        logErreurs.setForeground(new java.awt.Color(255, 0, 0));
        logErreurs.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("sansserif", 2, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Maintenez CTRL pour la sélection multiple");

        bouttonFermer.setBackground(new java.awt.Color(255, 204, 204));
        bouttonFermer.setText("Fermer");
        bouttonFermer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouttonFermerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpanelLayout = new javax.swing.GroupLayout(Jpanel);
        Jpanel.setLayout(JpanelLayout);
        JpanelLayout.setHorizontalGroup(
            JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(JpanelLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(barreNomGroupe, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelLayout.createSequentialGroup()
                            .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(logErreurs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(boutonCreerGroupe, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                .addComponent(bouttonFermer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        JpanelLayout.setVerticalGroup(
            JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barreNomGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(8, 8, 8)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boutonCreerGroupe, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(JpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bouttonFermer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logErreurs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Jpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void bouttonFermerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouttonFermerActionPerformed
        // TODO add your handling code here:
        Window parentWindow = SwingUtilities.windowForComponent((Component) evt.getSource());

        // Vérifiez si la fenêtre parente est une instance de JFrame
        if (parentWindow instanceof JFrame) {
            // Fermez la fenêtre parente (la fenêtre courante)
            parentWindow.dispose();    }
    }//GEN-LAST:event_bouttonFermerActionPerformed

    private void boutonCreerGroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonCreerGroupeActionPerformed
        String nomGroupe = barreNomGroupe.getText();

        // Vérifier si le nom du groupe est vide
        if (nomGroupe.isEmpty()) {
            // Afficher un message d'erreur ou prendre toute autre action nécessaire
            System.err.println("Le nom du groupe est vide !");
            logErreurs.setText("Le nom du groupe est vide !");
            return;
        }

        // récupére les adresses email des membres sélectionnés dans la JList
        int[] selectedIndices = contactsList.getSelectedIndices();
        List<String> emailsMembres = new ArrayList<>();
        for (int index : selectedIndices) {
            String selectedItem = contactsList.getModel().getElementAt(index);
            String[] parts = selectedItem.split(" - ");
            if (parts.length == 2) {
                emailsMembres.add(parts[1].trim());
            }
        }

        // Créer le groupe dans la base de données et récupérer son ID
        Bdd bdd = Bdd.getInstance();
        bdd.creerGroupe(nomGroupe);
        int idGroupe = bdd.getIdGroupeParNom(nomGroupe);

        logErreurs.setText("Groupe créé !");
        logErreurs.setForeground(GREEN);

        // Vérifier si le groupe a été créé avec succès
        if (idGroupe != -1) {
            // Créer une nouvelle conversation associée à ce groupe
            bdd.creerNouvelleConversationAvecGroupe(idGroupe);

            // Ajouter les membres au groupe
            bdd.ajouterMembresAuGroupe(nomGroupe, emailsMembres,emailUserCourant);
        } else {
            // Afficher un message d'erreur ou prendre toute autre action nécessaire
            System.err.println("Erreur lors de la création du groupe !");
            logErreurs.setText("Erreur lors de la création du groupe !");
        }

        this.dispose();

    }//GEN-LAST:event_boutonCreerGroupeActionPerformed

    private void barreNomGroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barreNomGroupeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barreNomGroupeActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Groupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Groupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Groupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Groupe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Groupe(contactsUserCourant,emailUserCourant).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jpanel;
    private javax.swing.JTextField barreNomGroupe;
    private javax.swing.JButton boutonCreerGroupe;
    private javax.swing.JButton bouttonFermer;
    private javax.swing.JList<String> contactsList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logErreurs;
    // End of variables declaration//GEN-END:variables
}
